set_temperature_with_end_datetime:
  target:
    entity:
      integration: bticino_x80000
      domain: climate
  fields:
    target_temperature:
      required: true
      example: "19.5"
      selector:
        number:
          min: 7
          max: 30
          step: 0.5
    end_datetime:
      required: true
      example: '"2019-04-20 05:04:20"'
      selector:
        datetime:

set_temperature_with_time_period:
  target:
    entity:
      integration: bticino_x80000
      domain: climate
  fields:
    target_temperature:
      required: true
      example: "19.5"
      selector:
        number:
          min: 7
          max: 30
          step: 0.5
    time_period:
      required: true
      default:
        hours: 3
        minutes: 0
        seconds: 0
        days: 0
      selector:
        duration:

set_boost_mode:
  target:
    entity:
      integration: bticino_x80000
      domain: climate
  fields:
    boost_mode:
      required: true
      example: "heat"
      selector:
        select:
          options:
            - "heating"
            - "cooling"
    boost_time:
      required: true
      selector:
        select:
          options:
            - 30
            - 60
            - 90

clear_temperature_setting:
  target:
    entity:
      integration: bticino_x80000
      domain: climate