set_turn_off_with_end_datetime:
  name: "Turn OFF thermostat with end datetime"
  description: "Turn OFF thermostat until the end date"
  target:
    entity:
      integration: bticino_x8000
      domain: climate
  fields:
    end_datetime:
      name: "End Datetime"
      description: "Set the end date"
      required: true
      example: '"2024-06-30 22:04:20"'
      selector:
        datetime:

set_turn_off_with_time_period:
  name: "Turn OFF thermostat with time period"
  description: "Turn OFF thermostat for time period"
  target:
    entity:
      integration: bticino_x8000
      domain: climate
  fields:
    time_period:
      name: "Time Period"
      description: "Set time period"
      required: true
      default:
        hours: 3
        minutes: 0
        seconds: 0
      selector:
        duration:

set_temperature_with_end_datetime:
  name: "Set temperature with end datetime"
  description: "Set the target temperature until the end date"
  target:
    entity:
      integration: bticino_x8000
      domain: climate
  fields:
    hvac_mode:
      name: "HVAC mode"
      description: "Set HVAC mode [HEATING/COOLING]"
      required: true
      example: "heating"
      selector:
        select:
          options:
            - "heating"
            - "cooling"
    target_temperature:
      name: "Target temperature"
      description: "Set the target temperature"
      required: true
      example: "19.5"
      selector:
        number:
          min: 7
          max: 40
          step: 0.5
    end_datetime:
      name: "End Datetime"
      description: "Set the end date"
      required: true
      example: '"2024-06-30 22:04:20"'
      selector:
        datetime:

set_temperature_with_time_period:
  name: "Set temperature with time period"
  description: "Set the target temperature for time period"
  target:
    entity:
      integration: bticino_x8000
      domain: climate
  fields:
    hvac_mode:
      name: "HVAC mode"
      description: "Set HVAC mode [HEATING/COOLING]"
      required: true
      example: "heating"
      selector:
        select:
          options:
            - "heating"
            - "cooling"
    target_temperature:
      name: "Target Temperature"
      description: "Set the target temperature"
      required: true
      example: "19.5"
      selector:
        number:
          min: 7
          max: 40
          step: 0.5
    time_period:
      name: "Time Period"
      description: "Set time period"
      required: true
      default:
        hours: 3
        minutes: 0
        seconds: 0
      selector:
        duration:

set_boost_mode:
  name: "Set BOOST mode"
  description: "Enable BOOST mode"
  target:
    entity:
      integration: bticino_x8000
      domain: climate
  fields:
    hvac_mode:
      name: "HVAC mode"
      description: "Set HVAC mode [HEATING/COOLING]"
      required: true
      example: "heating"
      selector:
        select:
          options:
            - "heating"
            - "cooling"
    boost_time:
      name: "BOOST Time"
      description: "Set the BOOST time period [30,60,90] min"
      required: true
      selector:
        select:
          options:
            - 30
            - 60
            - 90

set_schedule:
  target:
    entity:
      integration: bticino_x8000
      domain: climate
  fields:
    schedule_name:
      example: Standard
      required: true
      selector:
        text:
