set_temperature_with_end_datetime:
  name: "Set temperature with end datetime"
  description: "Set the target temperature until the end date"
  target:
    entity:
      integration: bticino_x80000
      domain: climate
  fields:
    target_temperature:
      name: "Target temperature"
      description: "Set the target temperature"
      required: true
      example: "19.5"
      selector:
        number:
          min: 7
          max: 40
          step: 0.5
    end_datetime:
      name: "End Datetime"
      description: "Set the end date"
      required: true
      example: '"2019-04-20 05:04:20"'
      selector:
        datetime:

set_temperature_with_time_period:
  name: "Set temperature with time period"
  description: "Set the target temperature for time period"
  target:
    entity:
      integration: bticino_x80000
      domain: climate
  fields:
    target_temperature:
      name: "Target Temperature"
      description: "Set the target temperature"
      required: true
      example: "19.5"
      selector:
        number:
          min: 7
          max: 40
          step: 0.5
    time_period:
      name: "Time Period"
      description: "Set time period"
      required: true
      default:
        hours: 3
        minutes: 0
        seconds: 0
        days: 0
      selector:
        duration:

set_boost_mode:
  name: "Set BOOST mode"
  description: "Enable BOOST mode"
  target:
    entity:
      integration: bticino_x80000
      domain: climate
  fields:
    boost_mode:
      name: "BOOST mode"
      description: "Set BOOST mode [HEATING/COOLING]"
      required: true
      example: "heat"
      selector:
        select:
          options:
            - "heating"
            - "cooling"
    boost_time:
      name: "BOOST Time"
      description: "Set the BOOST time period [30,60,90] min"
      required: true
      selector:
        select:
          options:
            - "30"
            - "60"
            - "90"

clear_temperature_setting:
  name: "Clear Temperature setting"
  description: "End all called services"
  target:
    entity:
      integration: bticino_x80000
      domain: climate