name: PR artifacts

on:
  pull_request:
    branches:
      - main

jobs:
  create:
    permissions:
      # Required to upload/save artifact, otherwise you'll get
      # "Error: Resource not accessible by integration"
      contents: write
      # Required to post comment, otherwise you'll get
      # "Error: Resource not accessible by integration"
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4

      - name: 📦 Create zip file for the integration
        run: |
          cd "${{ github.workspace }}/custom_components/bticino_x8000"
          zip bticino_x8000.zip -r ./
          mv bticino_x8000.zip "${{ github.workspace }}/"

      - name: 📤 Create comment with the artifiactory
        uses: gavv/pull-request-artifacts@v2
        with:
          # Commit hash that triggered PR
          commit: ${{ github.event.pull_request.head.sha }}

          # Token for current repo (used to post PR comment)
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          artifacts-branch: artifacts

          comment-title: |
            🤖 Pull request artifactsy

            For testing please download the zip file below and extract it in `[config folder]/custom_components/bticino_x8000`.

          # Whitespace-separated list of files to upload
          artifacts: |
            bticino_x8000.zip
